---
title: "bayesUpdating"
format: html
editor: visual
---

## Function to update an estimate of a 1-inflated beta distributed mean

```{r setup}
library(tidyverse)
library(MASS)

```

```{r nationalData}


# I will simulate som (national) data and then 
# test the wgt_mean function using simulated domain data
# The domain mean will be an area weighted mean of the domain data.
# The uncertainty around the domain estimate will use information
# about the shape of the national data distribution. 
# This information will count the equivalent of five domain spesific values,
# thus making it possieble to estimate domain distributions even with
# quite low n.

n <- 1000


national_data <- tibble(
  # first, some population samples with different properties
  uniform = runif(n, 0, 1),
  normal_centered = rnorm(n, 0.5, 0.2),
  normal_high = rnorm(n, 1, .5),
  beta_2_2 = rbeta(n, 2, 2),
  beta_05_3 = rbeta(n, .5, 3),
  beta_3_05 = rbeta(n, 3, .5),
  # add some area weights
  wgt = seq(1:n)
) |>
  # truncate
  mutate(across(
    !starts_with("wgt"),
    ~ case_when(
      . >= 1 ~ 1, #0.9999,  using pmin and pmax is another option
      . <= 0 ~ 0, #0.00001,
      .default = .
    )
  )) |>
  pivot_longer(
    cols = !starts_with("wgt"),
    names_to = "distribution",
    values_to = "population_sample"
  ) |>
  nest(population_sample = population_sample, wgt = wgt)

    
```

```{r domainData}


# pre set some sample sizes
a <- 2
b <- 5
c <- 10
d <- 30

domain_data <- tibble(
    sample_ID = c(
      "domain_1a",
      "domain_1b",
      "domain_1c",
      "domain_1d",
      "domain_2a",
      "domain_2b",
      "domain_2c",
      "domain_2d",
      "domain_3a",
      "domain_3b",
      "domain_3c",
      "domain_3d",
      "domain_4c",
      "domain_4d"),
    
    values = list(
      # 1's
      tibble(sample = rep(1,a)), 
      tibble(sample = rep(1,b)),
      tibble(sample = rep(1,c)),
      tibble(sample = rep(1,d)),
      
      #  high values
      tibble(sample = seq.int(0.7, 1, length.out=a)),
      tibble(sample = seq.int(0.7, 1, length.out=b)),
      tibble(sample = seq.int(0.7, 1, length.out=c)),
      tibble(sample = seq.int(0.7, 1, length.out=d)),
      
      #  low values (further from the population shape)
      tibble(sample = seq.int(0.1, 0.4, length.out=a)),
      tibble(sample = seq.int(0.1, 0.4, length.out=b)),
      tibble(sample = seq.int(0.1, 0.4, length.out=c)),
      tibble(sample = seq.int(0.1, 0.4, length.out=d)),
      
      # truncated normal, sorted to that we can test the effect of turning
       # weights on or off
      tibble(sample = rnorm(c, 1, .5) |> pmin(1) |> pmax(0) |> sort()),
      tibble(sample = rnorm(d, 1, .5) |> pmin(1) |> pmax(0) |> sort())
    ))


    
```

```{r tbl-showData}

DT::datatable(national_data)
```

```{r tbl-showData}

DT::datatable(domain_data)
```

```{r fig-plotDist}

# plot the population samples
national_data |>
  unnest(population_sample) |>
  ggplot()+
  geom_histogram(aes(x = population_sample),
                 binwidth = 0.1)+
  facet_wrap(vars(distribution),
             scales = "free")
#ggsave("../images/population_samples.png")
```

```{r fig-plotDist}

# plot the domain samples
domain_data |>
  unnest(values) |>
  ggplot()+
  geom_histogram(aes(x = sample),
                 binwidth = 0.1)+
  xlim(-0.2, 1.2)+
  facet_wrap(vars(sample_ID),
             scales = "free_y")
#ggsave("../images/population_samples.png")
```

```{r fit_zoib}
# function to fit zero and one inflated beta distributions
fit_zoib <- function(x) {
  prop_1 <- mean(x == 1)
  prop_0 <- mean(x == 0)
  x_trunc <- x[x > 0 & x < 1]
  alpha <- MASS::fitdistr(x_trunc, dbeta, start = list(shape1 = 1, shape2 = 1))$estimate
  list(alpha = alpha, prop_1 = prop_1, prop_0 = prop_0)
}


```

```{r}
# applied on the national dataset

national_data <- national_data |>
  rowwise() |>
  mutate(fit = 
           list(fit_zoib(unlist(population_sample))))

```



```{r updatingFunction}
# Empirical bayes
# Bayesian updating: combine domain data with national shape

update_distribution <- function(domain_data, national_fit, prior_weight = 5) {
  
  n <- length(domain_data)
  prop_1_domain <- mean(domain_data == 1)
  prop_0_domain <- mean(domain_data == 0)
  
  # Update 1-inflation (weighted average)
  updated_prop_1 <- (n * prop_1_domain + prior_weight * national_fit$prop_1) / (n + prior_weight)
  updated_prop_0 <- (n * prop_0_domain + prior_weight * national_fit$prop_0) / (n + prior_weight)
  
  # Update beta parameters (only for 0 < x < 1 part)
  x_trunc <- domain_data[domain_data > 0 & domain_data < 1]
  
  if (length(x_trunc) > 1) {
    tryCatch({
      alpha_domain <- MASS::fitdistr(x_trunc, dbeta, 
                                    start = list(shape1 = 1, shape2 = 1))$estimate
      
      updated_alpha <- (alpha_domain * length(x_trunc) + national_fit$alpha * prior_weight) /
                          (length(x_trunc) + prior_weight)
    }, error = function(msg){
      return(NA)
    }
      
    )
  } else {
    updated_alpha <- national_fit$alpha
  }
  
  if(!exists("updated_alpha")) updated_alpha <- NA
  
  list(
    alpha = updated_alpha, 
    prop_1 = updated_prop_1, 
    prop_0 = updated_prop_0
    )
}

#updated_dist <- update_distribution(domain_data, national_fit)
```

```{r}
# applied on the domain samples

comb_data <- domain_data |>
  cross_join(
    national_data)

comb_data <- comb_data |>
  rowwise() |>
  mutate(updated_fit = 
           list(
             update_distribution(
               domain_data = unlist(values),
               national_fit = fit
           )))
```

```{r simulationFunction}

# Generate uncertainty distribution around domain mean
simulate_domain <- function(dist, n_sim = 10000) {
  is_1 <- rbinom(n_sim, 1, dist$prop_1)
  is_0 <- rbinom(n_sim, 1, dist$prop_0) * (1 - is_1)
  cont_part <- (1 - is_1 - is_0) * rbeta(n_sim, dist$alpha[1], dist$alpha[2])
  is_1 * 1 + is_0 * 0 + cont_part
}

```

```{r}
# Applied on the test cases
comb_data <- comb_data |>
  rowwise() |>
  mutate(PDs = 
    list(simulate_domain(updated_fit, n_sim = 1000)))

```

```{r}
# add sample means (unweighted in this case)

comb_data <- comb_data |>
  mutate(
    mean = mean(unlist(values))
  )
```

```{r}

```


